language: python

python:
  - "3.4"

addons:
  postgresql: "9.3"

env: SECRET_KEY='dummy_secret' EMAIL_HOST_PASSWORD='dummy_password' DATABASE_URL=postgres://postgres@localhost/travis_ci_test PAYPAL_RECEIVER_EMAIL=dummy-email@hotmail.com PAYPAL_TEST=True DEFAULT_STUDIO_EMAIL=rebktest@gmail.com LOG_FOLDER=log_folder HEROKU=False

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install psycopg2

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate --settings=rebk.settings.base

script:
  - coverage run --source=products,orders,payments,gallery,accounts --omit=../*migrations*,../*tests*,../*wsgi*,../*__init__* manage.py test --settings=rebk.settings.base

after_success:
  coveralls
