# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 08:11
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20151031_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=40, populate_from='name', null=True),
        ),
    ]
