# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 09:10
from __future__ import unicode_literals

from django.db import migrations


def generate_slugs(apps, schema_editor):
    MyModel = apps.get_model('gallery', 'Category')
    for row in MyModel.objects.all():
        row.slug = row.name.replace(' ', '-')
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_category_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_code=migrations.RunPython.noop),
    ]
