# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_category_slug_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('id',)},
        ),
    ]
